### ISSUE TITLE
uitextfield SetLimit方法表情会有问题

### ISSUE THREAD

**Issue by IAskWind** [OctMon/OMExtension#1]
你好，当我在用textField.omSetLimit(6)的时候，我在文本框输入6个心的表情的时候（💗），再输入自动变成3个

**Comment by OctMon** [comment]
你好，感谢你的反馈，我已经解决这个bug
self.text = self.text!.substring(to: self.text!.index(self.text!.endIndex, offsetBy: -1))

**Comment by IAskWind** [comment]
你好，目前你这种改法，文本会有问题，联想输入，可以输入无限，在输入法里输入很多，最后按确认会与很多进去

**Comment by OctMon** [comment]
我增加检测表情
"♻️".omIsContainEmoji
我修改了文本长度的判断，因为一个表情占2个长度，当限制长度为6的时候，输入5个文字，最后输入一个表情会有问题！

**Comment by IAskWind** [comment]
那目前我如何用呢，我如果用SetLimit 表情就会有问题，因为我不知道用户到底输入什么呢，我目前就要控制具体的位数，所以有点不明白
